CREATE TABLE IF NOT EXISTS Posts (
post_id INTEGER PRIMARY KEY,
title TEXT NOT NULL,
body TEXT NOT NULL,
user_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Comments (
comment_id INTEGER PRIMARY KEY,
post_id INTEGER NOT NULL,
name TEXT NOT NULL,
email TEXT NOT NULL,
body TEXT NOT NULL
)